var commentList=["I look forward to helping",
"I look forward to seeing",
"look forward to helping her",
"look forward to helping him",
"I have enjoyed working with",
"I look forward to continuing",
"help when he needs it",
"look forward to seeing what",
"look forward to continuing to",
"I encourage her to continue",
"done a good job of",
"forward to seeing what he",
"well with the other students",
"forward to continuing to help",
"the final quarter of the",
"has done a good job",
"this year Have a great",
"for help when he needs",
"I encourage him to continue",
"so that she does not",
"forward to helping her continue",
"year I encourage him to",
"over the rest of the",
"what she needs to do",
"in the final quarter of",
"to seeing what he creates",
"look forward to seeing her",
"so that he does not",
"continue to make progress next",
"during the summer so that",
"I encourage him to do",
"this year I encourage him",
"look forward to her continued",
"forward to helping him make",
"have enjoyed working with her",
"to helping her continue to",
"she does not lose the",
"forward to helping him continue",
"her continue to make progress",
"him the best of luck",
"to helping him continue to",
"is a pleasure to teach",
"the rest of the year.",
"wish him the best of",
"after school to get help",
"helping her continue to make",
"to ask for help when",
"progress she has made this",
"been a pleasure to teach",
"to continuing to help him",
"has been a pleasure to",
"mathematics topics in a variety",
"does not lose the progress",
"works well with the other",
"in front of the class",
"from the beginning of the",
"be able to learn mathematics",
"when we return from our",
"has finished the year having",
"summer so that she does",
"topic areas To be successful",
"class I look forward to",
"of the course when we",
"problems they have never seen",
"at the end of the",
"does not forget what she",
"when we return to school",
"be successful students must be",
"her the best of luck",
"look forward to seeing his",
"he does not understand He",
"of mathematics topics in a",
"that she does not forget",
"reassess on the learning standards",
"and series the binomial theorem",
"high algebraic complexity and apply",
"college level development of mathematics",
"that she does not lose",
"am glad to be working",
"I am proud of her",
"development of mathematics topics in",
"we return to school in",
"of the course has focused",
"the summer so that she",
"areas To be successful students",
"successful students must be able",
"on mathematical sequences and series",
"get help when he needs",
"in a variety of topic",
"He works well with other",
"the course when we return",
"mathematics courses to problems they",
"level development of mathematics topics",
"course has focused on mathematical",
"second year of the course",
"the summer so that he",
"of topic areas To be",
"with the English language He",
"courses to problems they have",
"have never seen before The",
"a variety of topic areas",
"make progress when we return",
"to problems they have never",
"has made a strong effort",
"she does not forget what",
"to learn mathematics independently solve",
"variety of topic areas To",
"mathematics independently solve problems of",
"complexity and apply skills learned",
"stay after school to get",
"of high algebraic complexity and",
"when he needs it I",
"final quarter of the year.	",
"apply skills learned in previous",
"pleasure to teach I look",
"He should stay after school",
"has made an impressive effort",
"focused on mathematical sequences and",
"and proof by mathematical induction",
"students must be able to",
"a pleasure to teach I",
"previous mathematics courses to problems",
"numbers and proof by mathematical",
"and look forward to helping",
"has focused on mathematical sequences",
"to make the most of",
"HL course is a two",
"help when she needs it",
"I encourage her to make",
"questions when he needs help",
"I am glad to be",
"ask for help when he",
"has done excellent work this",
"in the final semester of",
"course is a two year",
"course at the standard level",
"I will continue to work",
"independently solve problems of high",
"sign up to reassess on",
"It is a pleasure to",
"the second year of the",
"wish her the best of",
"the best of luck in",
"algebraic complexity and apply skills",
"before The beginning of the",
"mathematical sequences and series the",
"The beginning of the course",
"topics in a variety of",
"learned in previous mathematics courses",
"and apply skills learned in",
"able to learn mathematics independently",
"should sign up to reassess",
"He is a pleasure to",
"next year Have a great",
"sequences and series the binomial",
"year college level development of",
"what he needs to do",
"she has made this year",
"series the binomial theorem complex",
"must be able to learn",
"have enjoyed working with him",
"has been a model student",
"in previous mathematics courses to",
"IB Mathematics HL course is",
"when she does not understand",
"learning standards of the course",
"binomial theorem complex numbers and",
"thus far in the course",
"complex numbers and proof by",
"as a web programmer He",
"to reassess on the learning",
"they have never seen before",
"solve problems of high algebraic",
"student I look forward to",
"Mathematics HL course is a",
"problems periodically during the summer",
"beginning of the course has",
"problems of high algebraic complexity",
"when he does not understand",
"for help when she needs",
"what he does not understand",
"encourage him to do so",
"seen before The beginning of",
"forward to helping her make",
"teach I look forward to",
"the course has focused on",
"after graduation Best of luck",
"is a two year college",
"with the other students to",
"skills learned in previous mathematics",
"works well with other students",
"year I look forward to",
"the basic requirements of projects",
"the binomial theorem complex numbers",
"to teach I look forward",
"To be successful students must",
"will continue to work with",
"glad to be working with",
"a two year college level",
"the beginning of the year",
"theorem complex numbers and proof",
"never seen before The beginning",
"to help her make progress",
"two year college level development",
"learn mathematics independently solve problems",
"this year I look forward",
"taken advantage of opportunities to",
"excellent work thus far in",
"periodically during the summer so",
"I look forward to",
"I encourage her to",
"I encourage him to",
"look forward to helping",
"look forward to seeing",
"forward to helping her",
"forward to helping him",
"he does not understand",
"the rest of the",
"have enjoyed working with",
"look forward to continuing",
"year Have a great",
"has done excellent work",
"help when he needs",
"a pleasure to teach",
"in this course He",
"and look forward to",
"when he needs it",
"the beginning of the",
"is a pleasure to",
"I have enjoyed working",
"I am proud of",
"He works well with",
"in the final quarter",
"when he needs help",
"the final quarter of",
"forward to continuing to",
"that she does not",
"done a good job",
"has continued to make",
"the best of luck",
"a good job of",
"forward to seeing what",
"has done a good",
"that he does not",
"encourage her to continue",
"for help when he",
"to develop his skills",
"this year Have a",
"so that she does",
"to continuing to help",
"encourage him to continue",
"when she needs it",
"well with the other",
"make the most of",
"what she needs to",
"has continued to do",
"on the learning standards",
"to seeing what he",
"the summer so that",
"to ask for help",
"final quarter of the",
"with the other students",
"problems on her own",
"when we return from",
"when we return in",
"she does not understand",
"at the beginning of",
"He still struggles with",
"does not lose the",
"I am glad to",
"year I encourage him",
"for help when she",
"in the second quarter.",
"has been a pleasure",
"in higher level mathematics",
"thus far in the",
"continue to make progress",
"on his own He",
"seeing what he creates",
"when we return to",
"she needs to do",
"over the rest of",
"so that he does",
"to helping her continue",
"on a regular basis",
"at the end of",
"progress when we return",
"forward to seeing her",
"has made this year",
"the end of the",
"as we move into",
"been a pleasure to",
"is a two year",
"her continue to make",
"wish him the best",
"encourage him to do",
"to make progress next",
"does not forget what",
"so that she is",
"the first quarter He",
"so that he can",
"summer so that he",
"forward to her continued",
"to be successful in",
"makes an effort to",
"this year I encourage",
"school to get help",
"his time at HIS",
"what he wants to",
"has made good progress",
"rest of the year.",
"she has made this",
"in this course She",
"progress she has made",
"as a way to",
"what he needs to",
"I will continue to",
"to make sure he",
"well with other students",
"to helping him make",
"to helping him continue",
"during the first quarter",
"him the best of",
"of the year She",
"she does not know",
"what he is learning",
"beginning of the course",
"ask for help when",
"and knows how to",
"continuing to help him",
"look forward to her",
"has made a good",
"in a way that",
"It is a pleasure",
"advantage of opportunities to",
"during the summer so",
"the class He has",
"helping him continue to",
"hope he continues to",
"and is able to",
"he needs to do",
"as a web programmer",
"with the English language",
"she does not lose",
"him to do so",
"I enjoy working with",
"after school to get",
"helping her continue to",
"enjoyed working with her",
"sense of humor and",
"I am confident that",
"has continued to struggle",
"taken advantage of opportunities",
"beginning of the year",
"working with him again",
"not forget what she",
"stay after school to",
"a two year college",
"what he does not",
"medical research papers and",
"To be successful students",
"year of the course",
"made an impressive effort",
"students must be able",
"mathematical sequences and series",
"work in this class",
"wish her the best",
"when he does not",
"level development of mathematics",
"get feedback on his",
"of the course has",
"with other students and",
"with her classmates to",
"has started the year",
"am glad to be",
"we return to school",
"needs to do to",
"before The beginning of",
"speaking in front of",
"not lose the progress",
"Tsz-Wai Suki has made",
"sequences and series the",
"never seen before The",
"year college level development",
"a variety of topic",
"student I look forward",
"pleasure to teach I",
"we return from our",
"mathematics independently solve problems",
"I wish her the",
"effort level in the",
"solve problems of high",
"helping her make progress",
"does not understand He",
"make progress when we",
"in a variety of",
"in front of the",
"college level development of",
"in the second year",
"the second year of",
"work on his own",
"to solve problems on",
"encourage her to make",
"glad to be working",
"has done good work",
"her the best of",
"in the process of",
"development of mathematics topics",
"forward to seeing his",
"learning standards of the",
"IB Mathematics HL course",
"He does not often",
"of the class He",
"to learn mathematics independently",
"have never seen before",
"when she does not",
"high algebraic complexity and",
"they have never seen",
"second year of the",
"quarter of the year.	",
"questions when he needs",
"has worked hard to",
"of the course when",
"to teach I look",
"the final semester of",
"and proof by mathematical",
"the course He has",
"make an effort to",
"continue to develop as",
"look forward to his",
"skills learned in previous",
"the other students and",
"has made a strong",
"learned in previous mathematics",
"needs to do for",
"in this class He",
"areas To be successful",
"should sign up to",
"to be working with",
"He should stay after",
"to work with him",
"algebraic complexity and apply",
"should do review problems",
"of mathematics topics in",
"reassess on the learning",
"to reassess on the",
"work this year He",
"and apply skills learned",
"series the binomial theorem",
"be able to learn",
"am proud of her",
"during class time He",
"in previous mathematics courses",
"work this semester He",
"I am here to",
"courses to problems they",
"asking her to do",
"of this course He",
"complexity and apply skills",
"HL course is a",
"works well with the",
"to take advantage of",
"I appreciate her efforts",
"a lot of time",
"of high algebraic complexity",
"class I look forward",
"on mathematical sequences and",
"He should make sure",
"the class and is",
"this year She is",
"the English language He",
"in the final semester",
"the binomial theorem complex",
"course is a two",
"has made an impressive",
"learn mathematics independently solve",
"on her own She",
"topics in a variety",
"will continue to work",
"graduation Best of luck",
"help her make progress",
"work thus far in",
"course at the standard",
"continue to work with",
"after graduation Best of",
"in the right direction",
"variety of topic areas",
"in order to improve",
"teach I look forward",
"excellent work this semester",
"standards of the course",
"must be able to",
"in asking for help",
"has finished the year",
"seen before The beginning",
"He does not always",
"effort during class and",
"has focused on mathematical",
"mathematics courses to problems",
"excellent work thus far",
"been a model student",
"work throughout the year",
"sign up to reassess",
"successful students must be",
"writing on the blog",
"complex numbers and proof",
"content of this course",
"to get feedback on",
"she does not forget",
"problems on his own",
"on her own to",
"course has focused on",
"be successful students must",
"and asks for help",
"apply skills learned in",
"far in the course",
"working with him this",
"to make the most",
"course when we return",
"and series the binomial",
"previous mathematics courses to",
"a lot of effort",
"Chen Yu Lucinda has",
"return to school in",
"theorem complex numbers and",
"next year Have a",
"topic areas To be",
"to practice his English",
"mathematics topics in a",
"this year I look",
"to helping her make",
"finished the year having",
"year Enjoy the summer!	",
"numbers and proof by",
"best of luck in",
"problems of high algebraic",
"front of the class",
"ask questions when he",
"basic requirements of projects",
"asks me for help",
"he is able to",
"what he has done",
"two year college level",
"summer so that she",
"get help when he",
"done excellent work this",
"Mathematics HL course is",
"enjoyed working with him",
"the course when we",
"works well with other",
"should stay after school",
"binomial theorem complex numbers",
"focused on mathematical sequences",
"Suki has made a",
"of topic areas To",
"has made a substantial",
"to problems they have",
"to stay after school",
"help when she needs",
"the other students to",
"He is a pleasure",
"from the beginning of",
"I first met him",
"I have enjoyed seeing",
"to ask questions and",
"me for help when",
"what she has learned",
"at the standard level",
"The beginning of the",
"made a strong effort",
"him make this progress",
"year I look forward",
"summer See you in",
"in the class and",
"a web programmer He",
"able to learn mathematics",
"the basic requirements of",
"up to reassess on",
"he needs it I",
"proof by mathematical induction",
"to help her make",
"interest in the course",
"problems periodically during the",
"the course has focused",
"his classmates He has",
"so that she can",
"is able to solve",
"this year He has",
"problems they have never",
"to apply them to",
"periodically during the summer",
"her understanding of the",
"has been a model",
"the level of work",
"independently solve problems of",
"during class and has",
"look forward to",
"I look forward",
"has continued to",
"encourage him to",
"encourage her to",
"I encourage her",
"I encourage him",
"forward to helping",
"of the course",
"he does not",
"on his own",
"forward to seeing",
"in this course",
"has made a",
"I have enjoyed",
"when he needs",
"she does not",
"does not understand",
"when we return",
"on her own",
"during class and",
"in the second",
"so that he",
"so that she",
"a pleasure to",
"Have a great",
"has done a",
"to help her",
"in the class",
"on his blog",
"to helping her",
"in the final",
"for help when",
"beginning of the",
"ask for help",
"in the course",
"He does not",
"is able to",
"a lot of",
"this course He",
"to helping him",
"has been a",
"rest of the",
"the beginning of",
"develop his skills",
"of the year",
"she needs to",
"in order to",
"works well with",
"help when he",
"in the future",
"an effort to",
"working with him",
"to do so",
"the rest of",
"needs to do",
"in class and",
"enjoyed working with",
"I appreciate her",
"a number of",
"forward to continuing",
"this year I",
"pleasure to teach",
"is a pleasure",
"to help him",
"level of effort",
"have enjoyed working",
"year Have a",
"to make progress",
"the final quarter",
"of the class",
"She works hard",
"in front of",
"has done excellent",
"done excellent work",
"to develop his",
"done a good",
"of this course",
"the first quarter",
"continued to make",
"He has not",
"as we move",
"this year He",
"he needs it",
"to be successful",
"throughout the year",
"the other students",
"in this class",
"what he is",
"and look forward",
"the basic requirements",
"this year and",
"I appreciate his",
"to solve problems",
"the best of",
"asks for help",
"will continue to",
"still struggles with",
"summer so that",
"a good job",
"that she does",
"to continuing to",
"he needs help",
"He works well",
"the class He",
"this semester He",
"the process of",
"Best of luck",
"her to continue",
"of the semester",
"some of the",
"the summer so",
"best of luck",
"working with her",
"to work with",
"to ask for",
"continue to develop",
"I am proud",
"that he does",
"knows how to",
"with her classmates",
"to seeing what",
"when she needs",
"am proud of",
"with other students",
"He has been",
"well with the",
"good job of",
"He has also",
"final quarter of",
"continue to make",
"the course He",
"he needs to",
"this course She",
"she has learned",
"year I encourage",
"him to continue",
"that he is",
"her continue to",
"her make progress",
"sense of humor",
"I am confident",
"I am glad",
"does not know",
"questions during class",
"this year Have",
"to get help",
"other students and",
"she needs it",
"after school to",
"we return in",
"the English language",
"during class She",
"we return from",
"what he knows",
"would benefit from",
"to improve her",
"the year She",
"what he has",
"the learning standards",
"to make sure",
"higher level mathematics",
"her effort level",
"on the learning",
"understanding of the",
"thus far in",
"continuing to help",
"quarter of the",
"class He has",
"this year She",
"to improve his",
"seeing what he",
"make the most",
"does not often",
"to understand the",
"to be a",
"over the past",
"am glad to",
"far in the",
"the most of",
"as much as",
"stay after school",
"the end of",
"with the other",
"year She is",
"him to do",
"what she needs",
"he has done",
"me for help",
"from the beginning",
"all of the",
"the material and",
"as a web",
"problems on her",
"her to do",
"requirements of projects",
"help from me",
"the standard level",
"that she is",
"continued to do",
"work this semester"
];
